pipeline:
  build:
    image: framgia/laravel-workspace
    branch: develop
    commands:
      - cp .env.example .env
      - composer install
      - php artisan migrate

services:
  database:
    image: mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: demo_db
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_pw
      MYSQL_ROOT_PASSWORD: root