build:
  image: framgia/laravel-workspace
  commands:
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - framgia-ci test-connect 127.0.0.1 3306 15
    - framgia-ci run

compose:
  database:
    image: mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: demo_db
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_pw
      MYSQL_ROOT_PASSWORD: root

cache:
  mount:
    - vendor
    - .git