build:
  image: framgia/laravel-workspace
  commands:
    - cp .env.example .env
    - composer install
    - framgia-ci test-connect 127.0.0.1 3306 60
    - framgia-ci run
compose:
  mysql_test:
    image: mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
cache:
  mount:
    - vendor
    - node_modules
    - .git