pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./vendor
    volumes:
      - /home/euclid/Project/drone/cache:/cache
  build:
    image: framgia/laravel-workspace
    commands:
      - cp .env.example .env
      - composer install
      - php artisan migrate
      - php vendor/bin/phpunit
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./vendor
    volumes:
      - /home/euclid/Project/drone/cache:/cache

services:
  database:
    image: mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: demo_db
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_pw
      MYSQL_ROOT_PASSWORD: root