build:
  image: framgia/laravel-workspace
  commands:
    - cp .env.example .env
    - composer install
    - framgia-ci test-connect 113.190.240.135
    - framgia-ci run

compose:
  database:
    image: mysql
    port:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

cache:
  mount:
    - vendor
    - .git