build:
  image: framgia/laravel-workspace
  commands:
    - cp .env.example .env
    - composer install
    - npm install
    - gulp
    - framgia-ci test-connect 127.0.0.1 3306 60
    - framgia-ci run
compose:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
cache:
  mount:
    - vendor
    - node_modules
    - .git